# Generated by Django 2.2.24 on 2022-08-02 06:44
import datetime

from django.db import migrations


def fill_field_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year > (datetime.datetime.now() - datetime.timedelta(days=365 * 7)).year:
            flat.new_building = True
            flat.save()
        else:
            flat.new_building = False
            flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0006_auto_20220802_0942'),
    ]

    operations = [
        migrations.RunPython(fill_field_new_building)
    ]
