# Generated by Django 2.2.24 on 2022-08-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20220803_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
