# Generated by Django 2.2.24 on 2022-08-04 03:37

from django.db import migrations
import phonenumbers


def owners_phonenumber_to_nomalized(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = phonenumbers.parse(flat.owners_phonenumber, "RU")
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0015_auto_20220804_0633'),
    ]

    operations = [
        migrations.RunPython(owners_phonenumber_to_nomalized)
    ]
