# Generated by Django 2.2.24 on 2022-08-04 04:25

from django.db import migrations


def flat_owners_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(full_name=flat.owner, phonenumber=flat.owners_phonenumber,
                                    pure_phone=flat.owner_pure_phone, flats=flat)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0018_owner'),
    ]

    operations = [
        migrations.RunPython(flat_owners_to_owner)
    ]
