# Generated by Django 2.2.24 on 2022-08-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20220804_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyOwnerOwnedFlats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'property_owner_owned_flats',
                'managed': False,
            },
        ),
    ]
