# Generated by Django 2.2.24 on 2022-08-04 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_propertyownerownedflats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyOwnerOwnedFlats',
        ),
    ]
