# Generated by Django 2.2.24 on 2022-08-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_delete_propertyownerownedflats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='flats',
        ),
        migrations.AddField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(related_name='owners_by_flat', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
