# Generated by Django 2.2.24 on 2022-08-05 05:10

from django.db import migrations


def flats_to_owners_flates(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        for flat in Flat.objects.filter(owner=owner.full_name):
            owner.flats.add(flat)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0023_auto_20220805_0810'),
    ]

    operations = [
        migrations.RunPython(flats_to_owners_flates)
    ]
